apiVersion: v2
name: llm-platform-poc
description: "Enterprise On-Prem LLM Platform — POC"
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: api-gateway
    version: "0.1.0"
    repository: "file://charts/api-gateway"
    condition: apiGateway.enabled
  - name: security-layer
    version: "0.1.0"
    repository: "file://charts/security-layer"
    condition: securityLayer.enabled
  - name: router
    version: "0.1.0"
    repository: "file://charts/router"
    condition: router.enabled
  - name: cache
    version: "0.1.0"
    repository: "file://charts/cache"
    condition: cache.enabled
  - name: inference-ollama
    version: "0.1.0"
    repository: "file://charts/inference-ollama"
    condition: inferenceOllama.enabled
  - name: agent-framework
    version: "0.1.0"
    repository: "file://charts/agent-framework"
    condition: agentFramework.enabled
  - name: model-registry
    version: "0.1.0"
    repository: "file://charts/model-registry"
    condition: modelRegistry.enabled
  - name: audit-store
    version: "0.1.0"
    repository: "file://charts/audit-store"
    condition: auditStore.enabled
  - name: admin-portal
    version: "0.1.0"
    repository: "file://charts/admin-portal"
    condition: adminPortal.enabled
  - name: observability
    version: "0.1.0"
    repository: "file://charts/observability"
    condition: observability.enabled
