apiVersion: v1
kind: Service
metadata:
  name: {{ include "admin-portal.fullname" . }}
  labels:
    {{- include "admin-portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8084
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: 9090
      protocol: TCP
  selector:
    {{- include "admin-portal.selectorLabels" . | nindent 4 }}
