apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "audit-store.fullname" . }}
  labels:
    {{- include "audit-store.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  selector:
    matchLabels:
      {{- include "audit-store.selectorLabels" . | nindent 6 }}
