apiVersion: v1
kind: Service
metadata:
  name: {{ include "security-layer.fullname" . }}
  labels:
    {{- include "security-layer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "security-layer.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
